id: '17211320218130.1752955184424141'
definitionId: chart
parentSlotId: '17194150364290.16855445806618063'
styles:
  xl:
    gridItem:
      x: 0
      y: 0
      w: 24
      h: 52
    flex:
      size:
        widthValue: 300
        widthUnit: px
        heightValue: 320
        heightUnit: px
      grow: '0'
      shrink: '0'
  xs:
    gridItem:
      x: 0
      y: 170
      w: 24
      h: 80
    flex:
      size:
        widthValue: 300
        widthUnit: px
        heightValue: 320
        heightUnit: px
      grow: '0'
      shrink: '0'
properties:
  dataset: '{{actions.loadProducts.data}}'
  config: |-
    {
      tooltip: {
        trigger: 'item'
      },
      series: [
        {
          name: 'Tasks status',
          type: 'pie',
          radius: ['40%', '70%'],
          avoidLabelOverlap: false,
          itemStyle: {
            borderRadius: 7,
            borderColor: '#fff',
            borderWidth: 2
          },
          label: {
            show: false,
            position: 'center'
          },
          labelLine: {
            show: false
          },
          color: ['#2c5cec', '#f32866', '#e8ad0e'],
          data: [
            { value: 10, name: 'In Progress'},
            { value:   10, name: 'Paused' },
            { value: 10, name: 'Backlog'},
          ]
        }
      ]
    };
  name: productsChart3
  __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
    - xl
    - xs
  title: Products
  type: barChart
  structure:
    - title: Product
      data: []
      color: primary
      xProp: productCode
      yProp: quantityInStock
      ignoreTimezone: false
      __UIBAKERY__SYSTEM_ID__: '17211320218570.7006046708793832'
      groupType: value
      groupFunctionType: count
  showLoading:
    withData: true
    dataValue: '{{actions.loadProducts.loading}}'
    value: false
  useJsConfig: echarts
actions: {}
slots: []
